root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
  sourceType: module
settings:
  react:
    version: detect
  import/core-modules:
    - react
    - styled-jsx/css
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - prettier
env:
  node: true
  browser: true
  es2021: true
  jest: true
rules:
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/indent': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/ban-types':
    - 2
    - types:
        Function: false
        Object: false
  '@typescript-eslint/no-unused-vars':
    - 2
    - argsIgnorePattern: '^_'
  import/no-extraneous-dependencies: 2 # very important!
  react/react-in-jsx-scope: off
  react/display-name: off
  react/prop-types: off
  'react-hooks/rules-of-hooks': error
  'react-hooks/exhaustive-deps': off
globals: {} # example: Cesium: true
