name: LintTypecheck

on:
  push:
    branches:
      - master
      - development

jobs:
  lintTypecheck:
    name: Lint and typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out monorepo
        uses: actions/checkout@v1
      - name: Install Node 14
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
          architecture: "x64" # (x64 or x86)
      - name: Install project dependencies
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.npmToken }}
        run: |
          npm install -g yarn
          yarn install
          yarn compile
      - name: Lint
        run: yarn lint
      - name: Typecheck
        run: yarn typecheck
