name: Tests

on:
  push:
    branches:
      - master
      - development

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out monorepo
        uses: actions/checkout@v1
      - name: Install Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64' # (x64 or x86)
      # - name: Install system-level dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt --assume-yes install libnetcdf-dev
      - name: Install project dependencies
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.npmToken }}
        run: |
          npm install -g yarn
          yarn install
      - name: Compile subpackages
        run: |
          yarn compileFast
      - name: Execute tests
        run: yarn test
